/**
 * The insight catalogue: how a business actually gets recommended by AI.
 *
 * This is the product's opinion, written down once and testable, rather than prose
 * regenerated by a model each time a customer asks.
 *
 * Every insight declares what it is grounded in, whether the business controls it, and how
 * we would know it worked. An insight that fails those three is advice, not a product
 * feature, and the difference matters: advice is what a customer can get free from a blog.
 *
 * The ordering principle throughout is honesty about leverage. The things that move AI
 * recommendations most for a local business are, in order: being unmistakably identifiable,
 * saying plainly what you are good for, and being consistent everywhere. Chasing coverage
 * you cannot control comes last, and is labelled as such.
 */
import type { Controllability } from '@autopilot/shared/domain.ts'

export type InsightCategory =
  | 'IDENTITY' // can an AI tell who and what you are?
  | 'ATTRIBUTES' // does it know what you are good for?
  | 'CONSISTENCY' // does your information agree with itself?
  | 'ACCESSIBILITY' // can it read your site at all?
  | 'STRUCTURE' // is the information machine-readable?
  | 'COVERAGE' // do the questions customers ask have answers on your site?
  | 'AUTHORITY' // does anyone else corroborate you?

export type Effort = 'MINUTES' | 'HOURS' | 'ONGOING'

export interface InsightStep {
  readonly he: string
  readonly en: string
}

export interface Insight {
  readonly key: string
  readonly category: InsightCategory
  readonly title: { he: string; en: string }
  /** Why this matters, in the customer's terms. Never SEO jargon. */
  readonly why: { he: string; en: string }
  /** Concrete steps. A business owner should be able to follow these without us. */
  readonly steps: readonly InsightStep[]
  readonly controllability: Controllability
  readonly effort: Effort
  /**
   * Expected leverage, 0..1. These are PRIORS, not measurements. The experiment engine
   * replaces them with observed outcomes as the dataset grows; until then they are stated
   * as beliefs and the UI presents them that way.
   */
  readonly expectedLeverage: number
  /** How the business would know it worked. An insight with no signal is not actionable. */
  readonly howYouWillKnow: { he: string; en: string }
  /** True when the product does this for the customer automatically. */
  readonly weDoThisForYou: boolean
  /** Verticals this applies to; empty means all. */
  readonly verticals: readonly string[]
}

export const INSIGHTS: readonly Insight[] = [
  {
    key: 'identity_clear',
    category: 'IDENTITY',
    title: {
      he: 'שיהיה ברור מי אתם ומה אתם עושים',
      en: 'Make it unmistakable who you are and what you do',
    },
    why: {
      he: 'לפני ש-AI ימליץ עליכם, הוא צריך להיות בטוח שהוא מדבר על העסק הנכון. אם השם, התחום והעיר לא מופיעים יחד במקום אחד ברור, המערכת מתלבטת — ובמקרה של ספק היא בוחרת עסק אחר.',
      en: 'Before an AI recommends you it has to be sure it is talking about the right business. If your name, category and city never appear together in one clear place, the system hesitates, and hesitation resolves in favour of a competitor.',
    },
    steps: [
      {
        he: 'בכותרת הדף הראשי כתבו: שם העסק - התחום - העיר. לדוגמה: "רוזה - מסעדה איטלקית בתל אביב".',
        en: 'Put this in your home page title: business name - what you are - city. For example: "Rosa - Italian restaurant in Tel Aviv".',
      },
      {
        he: 'בפסקה הראשונה באתר תארו את העסק במשפט אחד פשוט, בלי סופרלטיבים.',
        en: 'In the first paragraph on the site, describe the business in one plain sentence, with no superlatives.',
      },
      {
        he: 'ודאו שהעיר מופיעה בטקסט עצמו, לא רק בתמונה או בכתובת בתחתית העמוד.',
        en: 'Make sure the city appears in the text itself, not only in an image or in the footer address.',
      },
    ],
    controllability: 'CONTROLLED',
    effort: 'MINUTES',
    expectedLeverage: 0.9,
    howYouWillKnow: {
      he: 'העסק יתחיל להופיע בתשובות לשאלות כלליות על התחום שלכם בעיר.',
      en: 'You start appearing in answers to broad questions about your category in your city.',
    },
    weDoThisForYou: true,
    verticals: [],
  },
  {
    key: 'attributes_stated',
    category: 'ATTRIBUTES',
    title: {
      he: 'תכתבו במפורש למה אתם מתאימים',
      en: 'Say plainly what you are good for',
    },
    why: {
      he: 'זו הסיבה הנפוצה ביותר שעסקים טובים לא מומלצים. לקוחות לא שואלים "מסעדה בתל אביב" — הם שואלים "מסעדה רומנטית לדייט". אם האתר שלכם לא אומר את המילה "רומנטי" באף מקום, שום מערכת לא תמציא אותה עבורכם, גם אם זה נכון לחלוטין.',
      en: 'This is the single most common reason a good business is not recommended. Customers do not ask for "a restaurant in Tel Aviv", they ask for "a romantic restaurant for a date". If your site never says the word "romantic", no system will invent it for you, however true it is.',
    },
    steps: [
      {
        he: 'רשמו 5 סיבות אמיתיות שלקוחות בוחרים בכם. שאלו עובד ותיק אם אתם לא בטוחים.',
        en: 'Write down 5 real reasons customers choose you. Ask a long-serving employee if you are not sure.',
      },
      {
        he: 'לכל סיבה, כתבו באתר משפט אחד ישיר. "החדר שקט ומתאים לזוגות" עדיף על "אווירה ייחודית".',
        en: 'For each one, write a direct sentence on the site. "The room is quiet and suits couples" beats "a unique atmosphere".',
      },
      {
        he: 'אל תכתבו משהו שאינו נכון. אם תיכתב מילה שלא מתאימה, תקבלו לקוחות מאוכזבים וביקורות רעות.',
        en: 'Do not write anything that is not true. A word that does not fit brings disappointed customers and bad reviews.',
      },
    ],
    controllability: 'CONTROLLED',
    effort: 'HOURS',
    expectedLeverage: 0.85,
    howYouWillKnow: {
      he: 'תתחילו להופיע בשאלות ספציפיות — "לדייט", "עם ילדים", "לארוחה עסקית".',
      en: 'You start appearing in specific questions: "for a date", "with kids", "for a business lunch".',
    },
    weDoThisForYou: true,
    verticals: [],
  },
  {
    key: 'consistency_everywhere',
    category: 'CONSISTENCY',
    title: {
      he: 'שכל הפרטים יהיו זהים בכל מקום',
      en: 'Make every detail agree with itself everywhere',
    },
    why: {
      he: 'טלפון אחד באתר ואחר בגוגל, או שעות פתיחה שונות בפייסבוק — כל סתירה כזו מורידה את הביטחון של המערכת שמדובר באותו עסק. עסק שהמערכת לא בטוחה לגביו, היא פשוט לא מזכירה.',
      en: 'One phone number on your site and a different one on Google, or different opening hours on Facebook: every contradiction lowers a system’s confidence that these are the same business. A business it is unsure about is a business it simply does not mention.',
    },
    steps: [
      {
        he: 'פתחו את האתר, פרופיל Google, ופייסבוק זה לצד זה.',
        en: 'Open your site, your Google profile and Facebook side by side.',
      },
      {
        he: 'השוו: שם מדויק, טלפון, כתובת, שעות פתיחה. תקנו כל הבדל — גם הבדל בפורמט.',
        en: 'Compare: exact name, phone, address, opening hours. Fix every difference, including formatting.',
      },
      {
        he: 'עדכנו שעות מיוחדות בחגים. מידע שגוי על שעות עולה לכם בלקוחות מיידית.',
        en: 'Update holiday hours. Wrong hours cost you customers immediately.',
      },
    ],
    controllability: 'CONTROLLED',
    effort: 'MINUTES',
    expectedLeverage: 0.75,
    howYouWillKnow: {
      he: 'מדד דיוק המידע בדשבורד יעלה, ופחות תשובות יכילו פרטים שגויים עליכם.',
      en: 'The information-accuracy figure on your dashboard rises, and fewer answers state wrong details about you.',
    },
    weDoThisForYou: true,
    verticals: [],
  },
  {
    key: 'crawlable',
    category: 'ACCESSIBILITY',
    title: {
      he: 'ודאו שאפשר בכלל לקרוא את האתר',
      en: 'Make sure the site can be read at all',
    },
    why: {
      he: 'הרבה אתרים יפים בנויים כך שהטקסט נמצא בתוך תמונות, או נטען רק אחרי לחיצה. מבחינת מערכת שקוראת את האתר, הדף פשוט ריק.',
      en: 'Plenty of beautiful sites keep their text inside images, or load it only after a click. To a system reading the page, it is simply blank.',
    },
    steps: [
      {
        he: 'פתחו את האתר, לחצו ימני ובחרו "הצג מקור הדף". חפשו את שם העסק והתיאור. אם הם לא שם — הם לא קיימים.',
        en: 'Open your site, right-click and choose "View page source". Search for your business name and description. If they are not there, they do not exist.',
      },
      {
        he: 'לכל תמונה עם טקסט חשוב — הוסיפו את אותו טקסט גם ככתב רגיל בדף.',
        en: 'For every image containing important text, add the same text as real text on the page.',
      },
      {
        he: 'בדקו שהאתר נטען גם בחיבור איטי. דף שלא נטען הוא דף שלא נקרא.',
        en: 'Check the site loads on a slow connection. A page that does not load is a page that is not read.',
      },
    ],
    controllability: 'CONTROLLED',
    effort: 'HOURS',
    expectedLeverage: 0.7,
    howYouWillKnow: {
      he: 'מספר העמודים שאנחנו מצליחים לקרוא באתר יעלה.',
      en: 'The number of pages we can successfully read on your site goes up.',
    },
    weDoThisForYou: false,
    verticals: [],
  },
  {
    key: 'structured_data',
    category: 'STRUCTURE',
    title: {
      he: 'תנו למכונה גרסה מסודרת של הפרטים',
      en: 'Give machines a tidy copy of your details',
    },
    why: {
      he: 'יש פורמט תקני שבו אפשר לרשום שם, כתובת, שעות ותחום כך שמערכת תקרא אותם בוודאות במקום לנחש מהטקסט. זה לא טריק — זה פשוט אותו מידע, בצורה שאי אפשר לטעות בה.',
      en: 'There is a standard format for stating your name, address, hours and category so a system reads them with certainty instead of guessing from prose. It is not a trick: it is the same information, in a form that cannot be misread.',
    },
    steps: [
      {
        he: 'אנחנו מייצרים את זה עבורכם אוטומטית מהפרטים שאישרתם — אין מה לעשות ידנית.',
        en: 'We generate this for you automatically from the details you confirmed. Nothing to do by hand.',
      },
      {
        he: 'חשוב: הפורמט הזה חייב להתאים למה שכתוב בדף. אל תרשמו בו מידע שלא מופיע באתר.',
        en: 'Important: this must match what the page actually says. Never state information in it that is not on the site.',
      },
    ],
    controllability: 'CONTROLLED',
    effort: 'MINUTES',
    expectedLeverage: 0.55,
    howYouWillKnow: {
      he: 'פחות תשובות יתארו אתכם בצורה חלקית או שגויה.',
      en: 'Fewer answers describe you partially or incorrectly.',
    },
    weDoThisForYou: true,
    verticals: [],
  },
  {
    key: 'answer_the_questions',
    category: 'COVERAGE',
    title: {
      he: 'תענו באתר על השאלות שלקוחות באמת שואלים',
      en: 'Answer on your site the questions customers actually ask',
    },
    why: {
      he: 'מערכת שמחפשת תשובה לשאלה ספציפית מעדיפה מקור שעונה עליה במפורש. אם באתר שלכם אין תשובה ל"יש חניה?" או "אפשר עם כלב?" — היא תיקח את התשובה ממישהו אחר, ותמליץ עליו.',
      en: 'A system looking for the answer to a specific question prefers a source that answers it outright. If your site does not say whether there is parking, or whether dogs are welcome, it takes the answer from someone else and recommends them.',
    },
    steps: [
      {
        he: 'רשמו את 10 השאלות שהכי שואלים אתכם בטלפון. אלה בדיוק השאלות ששואלים AI.',
        en: 'Write down the 10 questions you are asked most on the phone. Those are exactly the questions people ask an AI.',
      },
      {
        he: 'הוסיפו לאתר עמוד שאלות ותשובות עם תשובה ישירה וקצרה לכל אחת.',
        en: 'Add a questions-and-answers page with a short, direct answer to each.',
      },
      {
        he: 'תשובה של שתי שורות עדיפה על פסקה שיווקית. תכתבו כמו שאתם עונים בטלפון.',
        en: 'A two-line answer beats a marketing paragraph. Write it the way you answer on the phone.',
      },
    ],
    controllability: 'CONTROLLED',
    effort: 'HOURS',
    expectedLeverage: 0.65,
    howYouWillKnow: {
      he: 'תתחילו להופיע בשאלות עם תנאי — "עם חניה", "פתוח עכשיו", "מתאים לילדים".',
      en: 'You start appearing in questions with conditions: "with parking", "open now", "suitable for children".',
    },
    weDoThisForYou: true,
    verticals: [],
  },
  {
    key: 'google_profile',
    category: 'IDENTITY',
    title: {
      he: 'תחזקו את פרופיל Google שלכם',
      en: 'Keep your Google profile in order',
    },
    why: {
      he: 'עבור עסק מקומי, פרופיל Google הוא לרוב המקור החיצוני שהמערכות סומכות עליו הכי הרבה. פרופיל מאומת ומעודכן שווה יותר מכל טקסט שיווקי באתר.',
      en: 'For a local business the Google profile is usually the outside source these systems trust most. A verified, current profile is worth more than any amount of marketing copy on your site.',
    },
    steps: [
      {
        he: 'ודאו שהעסק מאומת. פרופיל לא מאומת נחשב פחות.',
        en: 'Make sure the business is verified. An unverified profile counts for less.',
      },
      {
        he: 'מלאו את הקטגוריה הראשית במדויק, את השעות ואת כל התכונות הרלוונטיות.',
        en: 'Fill in the primary category accurately, the hours, and every relevant attribute.',
      },
      {
        he: 'ענו לביקורות — גם לשליליות, בנימוס ובלי להתווכח.',
        en: 'Reply to reviews, including negative ones, politely and without arguing.',
      },
    ],
    controllability: 'INFLUENCEABLE',
    effort: 'ONGOING',
    expectedLeverage: 0.7,
    howYouWillKnow: {
      he: 'יותר תשובות יצטטו מקורות שמזכירים אתכם.',
      en: 'More answers cite sources that mention you.',
    },
    weDoThisForYou: false,
    verticals: [],
  },
  {
    key: 'external_coverage',
    category: 'AUTHORITY',
    title: {
      he: 'אזכורים חיצוניים — חשוב, אבל לא בשליטתנו',
      en: 'Outside coverage matters, and is not ours to control',
    },
    why: {
      he: 'כשמקור עצמאי כותב עליכם, זה מחזק את מה שאתם אומרים על עצמכם. זה משפיע — ואנחנו לא יכולים לייצר את זה עבורכם, ולא ננסה. כל מי שמבטיח לכם "אזכורים" בתשלום מוכר לכם בעיה עתידית.',
      en: 'When an independent source writes about you, it corroborates what you say about yourself. It genuinely matters, and we cannot manufacture it for you, and will not try. Anyone selling you paid "mentions" is selling you a future problem.',
    },
    steps: [
      {
        he: 'הדרך האמיתית: לעשות עבודה טובה, ולבקש מלקוחות מרוצים לכתוב ביקורת אמיתית — בלי תמורה.',
        en: 'The real route: do good work, and ask satisfied customers for an honest review, with nothing offered in return.',
      },
      {
        he: 'אם אתם עושים משהו שבאמת מעניין, פנו לעיתונות מקומית או לבלוגרים בתחום.',
        en: 'If you are doing something genuinely interesting, approach local press or writers in your field.',
      },
      {
        he: 'הירשמו למדריכים הרלוונטיים לתחום שלכם. זה חינם ובשליטתכם.',
        en: 'List yourself in the directories relevant to your field. That part is free and within your control.',
      },
    ],
    controllability: 'NOT_CONTROLLED',
    effort: 'ONGOING',
    expectedLeverage: 0.8,
    howYouWillKnow: {
      he: 'מספר המקורות החיצוניים שמזכירים אתכם בתשובות יעלה.',
      en: 'The number of outside sources mentioning you in answers goes up.',
    },
    weDoThisForYou: false,
    verticals: [],
  },
  {
    key: 'never_do_this',
    category: 'AUTHORITY',
    title: {
      he: 'ומה שלא לעשות בשום אופן',
      en: 'And what never to do',
    },
    why: {
      he: 'יש שיטות שנראות כמו קיצור דרך ועובדות לזמן קצר. כשהן מתגלות, העסק משלם — ולא רק בנראות. אנחנו לא עושים אף אחת מהן, וכדאי שגם אתם לא.',
      en: 'Some methods look like shortcuts and work briefly. When they are caught, the business pays, and not only in visibility. We do none of them, and neither should you.',
    },
    steps: [
      {
        he: 'ביקורות מזויפות או בתמורה להטבה — אסור, ומזוהה.',
        en: 'Fake reviews, or reviews in exchange for a benefit: prohibited, and detected.',
      },
      {
        he: 'טקסט מוסתר בדף שנועד "לדבר אל ה-AI" — מזוהה, ופוגע באמון.',
        en: 'Hidden text on the page meant to "talk to the AI": detected, and it destroys trust.',
      },
      {
        he: 'עשרות עמודים כמעט זהים לכל עיר או שירות — מזוהה כספאם.',
        en: 'Dozens of near-identical pages for every city or service: recognised as spam.',
      },
      {
        he: 'פרסים והמלצות שלא היו — הדבר הכי מסוכן. לקוח אחד שיבדוק מספיק.',
        en: 'Awards and endorsements that never happened: the most dangerous of all. One customer checking is enough.',
      },
    ],
    controllability: 'CONTROLLED',
    effort: 'MINUTES',
    expectedLeverage: 0.5,
    howYouWillKnow: {
      he: 'לא תיפגעו. זו הגנה, לא שיפור.',
      en: 'You do not get hurt. This is protection, not improvement.',
    },
    weDoThisForYou: true,
    verticals: [],
  },
]

export const insightsFor = (vertical: string): readonly Insight[] =>
  INSIGHTS.filter((i) => i.verticals.length === 0 || i.verticals.includes(vertical))

/**
 * Ranked for a specific business.
 *
 * Weighted so that something we can act on today outranks something with a higher ceiling
 * that depends on other people. A list topped by "get press coverage" is a list that makes
 * a customer feel stuck.
 */
export const prioritizedInsights = (
  vertical: string,
  options: { readonly weakCategories?: readonly InsightCategory[] } = {},
): readonly Insight[] => {
  const weak = new Set(options.weakCategories ?? [])
  const controlWeight: Record<Controllability, number> = {
    CONTROLLED: 1,
    INFLUENCEABLE: 0.6,
    NOT_CONTROLLED: 0.3,
  }
  const effortWeight: Record<Effort, number> = { MINUTES: 1, HOURS: 0.85, ONGOING: 0.6 }

  return [...insightsFor(vertical)].sort((a, b) => {
    const score = (i: Insight): number =>
      i.expectedLeverage *
      controlWeight[i.controllability] *
      effortWeight[i.effort] *
      // A weakness we actually measured outranks a general prior.
      (weak.has(i.category) ? 1.5 : 1)
    return score(b) - score(a)
  })
}
