/**
 * Business Model - Core entity for multi-tenant system
 * Each business has its own AI bot configuration
 */

const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid');

const BusinessHoursSchema = new mongoose.Schema({
  day: {
    type: String,
    enum: ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
    required: true
  },
  isOpen: { type: Boolean, default: true },
  openTime: { type: String, default: '09:00' },
  closeTime: { type: String, default: '22:00' }
}, { _id: false });

const FAQSchema = new mongoose.Schema({
  question: { type: String, required: true },
  answer: { type: String, required: true },
  keywords: [String],
  usageCount: { type: Number, default: 0 },
  lastUsed: Date,
  isAutoGenerated: { type: Boolean, default: false }
}, { timestamps: true });

const MenuItemSchema = new mongoose.Schema({
  name: { type: String, required: true },
  nameHebrew: { type: String, required: true },
  description: String,
  descriptionHebrew: String,
  price: Number,
  category: String,
  isAvailable: { type: Boolean, default: true },
  allergens: [String],
  isVegan: { type: Boolean, default: false },
  isVegetarian: { type: Boolean, default: false },
  isGlutenFree: { type: Boolean, default: false }
}, { _id: true });

const ReservationSettingsSchema = new mongoose.Schema({
  enabled: { type: Boolean, default: true },
  maxPartySize: { type: Number, default: 20 },
  minPartySize: { type: Number, default: 1 },
  advanceBookingDays: { type: Number, default: 30 },
  timeSlotDuration: { type: Number, default: 30 }, // minutes
  requirePhoneNumber: { type: Boolean, default: true },
  requireEmail: { type: Boolean, default: false },
  confirmationMessage: {
    type: String,
    default: 'ההזמנה שלך אושרה! נשמח לראותך.'
  },
  blockedDates: [Date]
}, { _id: false });

const BotPersonalitySchema = new mongoose.Schema({
  name: { type: String, default: 'שירה' },
  gender: { type: String, enum: ['male', 'female'], default: 'female' },
  tone: {
    type: String,
    enum: ['professional', 'friendly', 'casual'],
    default: 'friendly'
  },
  greetingMessage: {
    type: String,
    default: 'שלום! הגעת ל{businessName}. איך אוכל לעזור לך היום?'
  },
  goodbyeMessage: {
    type: String,
    default: 'תודה שהתקשרת! יום נעים.'
  },
  holdMessage: {
    type: String,
    default: 'רגע אחד בבקשה, אני בודקת את המידע.'
  },
  notUnderstoodMessage: {
    type: String,
    default: 'סליחה, לא הבנתי. אפשר לחזור על זה?'
  },
  customInstructions: String
}, { _id: false });

const BillingSchema = new mongoose.Schema({
  plan: {
    type: String,
    enum: ['starter', 'professional', 'enterprise'],
    default: 'starter'
  },
  monthlyPrice: { type: Number, default: 1200 },
  minutesIncluded: { type: Number, default: 500 },
  pricePerExtraMinute: { type: Number, default: 0.5 },
  stripeCustomerId: String,
  stripeSubscriptionId: String,
  billingCycleStart: Date,
  nextBillingDate: Date,
  isActive: { type: Boolean, default: true },
  paymentMethod: String
}, { _id: false });

const BusinessSchema = new mongoose.Schema({
  // Unique identifier for webhook routing
  botId: {
    type: String,
    unique: true,
    default: () => uuidv4().split('-')[0]
  },

  // Basic Information
  name: {
    type: String,
    required: [true, 'Business name is required'],
    trim: true
  },
  nameHebrew: {
    type: String,
    required: [true, 'Hebrew business name is required'],
    trim: true
  },
  type: {
    type: String,
    enum: ['restaurant', 'cafe', 'bar', 'clinic', 'salon', 'hotel', 'service', 'other'],
    default: 'restaurant'
  },
  description: String,
  descriptionHebrew: String,

  // Contact Information
  phone: {
    type: String,
    required: [true, 'Business phone is required']
  },
  twilioPhoneNumber: {
    type: String,
    unique: true,
    sparse: true
  },
  email: String,
  website: String,

  // Location
  address: {
    street: String,
    city: String,
    postalCode: String,
    country: { type: String, default: 'Israel' }
  },

  // Business Hours
  businessHours: {
    type: [BusinessHoursSchema],
    default: [
      { day: 'sunday', isOpen: true, openTime: '09:00', closeTime: '22:00' },
      { day: 'monday', isOpen: true, openTime: '09:00', closeTime: '22:00' },
      { day: 'tuesday', isOpen: true, openTime: '09:00', closeTime: '22:00' },
      { day: 'wednesday', isOpen: true, openTime: '09:00', closeTime: '22:00' },
      { day: 'thursday', isOpen: true, openTime: '09:00', closeTime: '22:00' },
      { day: 'friday', isOpen: true, openTime: '09:00', closeTime: '15:00' },
      { day: 'saturday', isOpen: false, openTime: '20:00', closeTime: '23:00' }
    ]
  },

  // Menu/Services (for restaurants)
  menuItems: [MenuItemSchema],
  menuCategories: [String],

  // FAQ & Knowledge Base
  faqs: [FAQSchema],

  // Reservation Settings
  reservationSettings: {
    type: ReservationSettingsSchema,
    default: () => ({})
  },

  // Bot Configuration
  botPersonality: {
    type: BotPersonalitySchema,
    default: () => ({})
  },

  // AI Configuration
  aiConfig: {
    useGPT4ForComplex: { type: Boolean, default: false },
    maxResponseTokens: { type: Number, default: 150 },
    temperature: { type: Number, default: 0.7 },
    enableSentimentAnalysis: { type: Boolean, default: true },
    enableAutoFAQ: { type: Boolean, default: true }
  },

  // Voice Configuration
  voiceConfig: {
    language: { type: String, default: 'he-IL' },
    voiceName: { type: String, default: 'he-IL-Wavenet-A' }, // Female Hebrew voice
    speakingRate: { type: Number, default: 1.0 },
    pitch: { type: Number, default: 0 }
  },

  // Billing
  billing: {
    type: BillingSchema,
    default: () => ({})
  },

  // Statistics (updated in real-time)
  stats: {
    totalCalls: { type: Number, default: 0 },
    totalMinutes: { type: Number, default: 0 },
    totalReservations: { type: Number, default: 0 },
    totalCost: { type: Number, default: 0 },
    avgCallDuration: { type: Number, default: 0 },
    successRate: { type: Number, default: 0 },
    lastCallAt: Date
  },

  // Owner/Client
  owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },

  // Status
  isActive: { type: Boolean, default: true },
  isPaused: { type: Boolean, default: false },
  pauseReason: String,

  // Missing Information Suggestions
  missingInfo: [{
    field: String,
    suggestion: String,
    priority: { type: String, enum: ['low', 'medium', 'high'], default: 'medium' },
    detectedAt: { type: Date, default: Date.now }
  }],

  // Metadata
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  notes: String

}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Indexes for performance
BusinessSchema.index({ botId: 1 });
BusinessSchema.index({ owner: 1 });
BusinessSchema.index({ twilioPhoneNumber: 1 });
BusinessSchema.index({ isActive: 1, isPaused: 1 });
BusinessSchema.index({ 'billing.plan': 1 });

// Virtual for webhook URL
BusinessSchema.virtual('webhookUrl').get(function() {
  return `${process.env.API_URL}/webhook/${this.botId}`;
});

// Virtual for current month usage
BusinessSchema.virtual('currentMonthMinutes').get(function() {
  // This would be calculated from calls collection
  return this.stats.totalMinutes;
});

// Method to check if business is currently open
BusinessSchema.methods.isCurrentlyOpen = function() {
  const moment = require('moment-timezone');
  const now = moment().tz('Asia/Jerusalem');
  const dayName = now.format('dddd').toLowerCase();
  
  const todayHours = this.businessHours.find(h => h.day === dayName);
  if (!todayHours || !todayHours.isOpen) return false;
  
  const currentTime = now.format('HH:mm');
  return currentTime >= todayHours.openTime && currentTime <= todayHours.closeTime;
};

// Method to get greeting based on time
BusinessSchema.methods.getTimeBasedGreeting = function() {
  const moment = require('moment-timezone');
  const hour = moment().tz('Asia/Jerusalem').hour();
  
  if (hour < 12) return 'בוקר טוב';
  if (hour < 17) return 'צהריים טובים';
  if (hour < 21) return 'ערב טוב';
  return 'לילה טוב';
};

// Pre-save middleware to generate botId
BusinessSchema.pre('save', function(next) {
  if (!this.botId) {
    this.botId = uuidv4().split('-')[0];
  }
  next();
});

module.exports = mongoose.model('Business', BusinessSchema);
